//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.16 at 12:03:33 AM IST 
//


package com.iit.xmldb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.iit.xmldb.EmpInfoType;
import com.iit.xmldb.ProjectTimeSheetType;


/**
 * <p>Java class for EmpInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmpInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GuideName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmpName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmpId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProjectTimeSheet" type="{http://com/iit/xmldb/TimeSheetInfo}ProjectTimeSheetType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TotalHours" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "EmpInfoType", propOrder = {
    "guideName",
    "empName",
    "empId",
    "projectTimeSheet",
    "totalHours"
})
public class EmpInfoType {

    @XmlElement(name = "GuideName", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String guideName;
    @XmlElement(name = "EmpName", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String empName;
    @XmlElement(name = "EmpId", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String empId;
    @XmlElement(name = "ProjectTimeSheet", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected List<ProjectTimeSheetType> projectTimeSheet;
    @XmlElement(name = "TotalHours", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String totalHours;

    /**
     * Gets the value of the guideName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuideName() {
        return guideName;
    }

    /**
     * Sets the value of the guideName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuideName(String value) {
        this.guideName = value;
    }

    /**
     * Gets the value of the empName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * Sets the value of the empName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpName(String value) {
        this.empName = value;
    }

    /**
     * Gets the value of the empId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpId(String value) {
        this.empId = value;
    }

    /**
     * Gets the value of the projectTimeSheet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectTimeSheet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProjectTimeSheet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectTimeSheetType }
     * 
     * 
     */
    public List<ProjectTimeSheetType> getProjectTimeSheet() {
        if (projectTimeSheet == null) {
            projectTimeSheet = new ArrayList<ProjectTimeSheetType>();
        }
        return this.projectTimeSheet;
    }

    /**
     * Gets the value of the totalHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalHours() {
        return totalHours;
    }

    /**
     * Sets the value of the totalHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalHours(String value) {
        this.totalHours = value;
    }

}
