//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.16 at 12:03:33 AM IST 
//


package com.iit.xmldb;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.iit.xmldb.ProjectTimeSheetType;


/**
 * <p>Java class for ProjectTimeSheetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectTimeSheetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProjectCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActivityHeading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ActivityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WorkingHours" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "ProjectTimeSheetType", propOrder = {
    "projectCode",
    "activityHeading",
    "activityName",
    "description",
    "startDate",
    "workingHours"
})
public class ProjectTimeSheetType {

    @XmlElement(name = "ProjectCode", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String projectCode;
    @XmlElement(name = "ActivityHeading", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String activityHeading;
    @XmlElement(name = "ActivityName", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String activityName;
    @XmlElement(name = "Description", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String description;
    @XmlElement(name = "StartDate", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String startDate;
    @XmlElement(name = "WorkingHours", namespace = "http://com/iit/xmldb/TimeSheetInfo")
    protected String workingHours;

    /**
     * Gets the value of the projectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * Sets the value of the projectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectCode(String value) {
        this.projectCode = value;
    }

    /**
     * Gets the value of the activityHeading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityHeading() {
        return activityHeading;
    }

    /**
     * Sets the value of the activityHeading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityHeading(String value) {
        this.activityHeading = value;
    }

    /**
     * Gets the value of the activityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * Sets the value of the activityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivityName(String value) {
        this.activityName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the workingHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkingHours() {
        return workingHours;
    }

    /**
     * Sets the value of the workingHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkingHours(String value) {
        this.workingHours = value;
    }

}
