//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.02.22 at 12:06:16 AM IST 
//


package com.iit.xmldb;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.iit.xmldb.EmpType;


/**
 * <p>Java class for EmpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmpId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Salary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Adrs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "EmpType", propOrder = {
    "name",
    "age",
    "empId",
    "salary",
    "adrs"
})
public class EmpType {

    @XmlElement(name = "Name", namespace = "http://com/iit/xmldb/EmpInfo")
    protected String name;
    @XmlElement(name = "Age", namespace = "http://com/iit/xmldb/EmpInfo")
    protected String age;
    @XmlElement(name = "EmpId", namespace = "http://com/iit/xmldb/EmpInfo")
    protected String empId;
    @XmlElement(name = "Salary", namespace = "http://com/iit/xmldb/EmpInfo")
    protected String salary;
    @XmlElement(name = "Adrs", namespace = "http://com/iit/xmldb/EmpInfo")
    protected String adrs;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the empId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * Sets the value of the empId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpId(String value) {
        this.empId = value;
    }

    /**
     * Gets the value of the salary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalary() {
        return salary;
    }

    /**
     * Sets the value of the salary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalary(String value) {
        this.salary = value;
    }

    /**
     * Gets the value of the adrs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdrs() {
        return adrs;
    }

    /**
     * Sets the value of the adrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdrs(String value) {
        this.adrs = value;
    }

}
